spring:
  application:
    name: starwars-backend

api:
  swapi:
    base-url: https://swapi.tech/api
    response-timeout: 5s
    connect-timeout: 5s

cache:
  caffeine:
    expire-after-write: 1d
    maximum-size: 1000
    names: people
